# ------------------------------------------------------------------
# Pipeline: Backend Function Deployment
# Description: Deploys the backend Azure Function app on pushes to main branch
# Triggers on changes in backend directory and pipeline YAML file
# ------------------------------------------------------------------

name: backend-function-deploy
trigger:
  branches:
    include:
    - main

  paths:
    include:
      - backend/**
      - azure-pipelines-function-deploy.yml

# Use local agent 
pool:
  name: 'Default'

jobs:
  - job: deploy_function
    displayName: Deploy Backend Function
    pool: 
      name: 'Default'

    steps:
      # Checkout repository source code
      # GitHub Actions 'actions/checkout@v3' replaced by Azure DevOps 'checkout: self'
      - checkout: self
      
      # GitHub Actions 'actions/setup-python@v4' replaced by Azure DevOps task
      #- task: UsePythonVersion@0
      #  inputs:
      #    versionSpec: '3.10'
      #    addToPath: true
      
          
      # Masking secrets: Azure DevOps does not support echo "::add-mask::" syntax.
      # Instead, secrets are automatically masked in logs when referenced as variables.
      # So secrets should be defined in Azure DevOps Library or Pipeline variables.

      # Install Azure Functions Core Tools (equivalent to GitHub workflow script)
      - powershell: |
          choco install azure-functions-core-tools-4 -y
        displayName: 'Install Azure Functions Core Tools'

      # Azure Login: In Azure DevOps, use AzureCLI@2 task for login instead of azure/login@v1 GitHub Action
      # use ps instead of bash as local agent is on windows
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'ubds-sp-connection'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            Write-Host "Logged in to Azure CLI"

      # Install Python dependencies and deploy the Azure Function app
      - powershell:: |
          pip install -r backend/requirements.txt
          func azure functionapp publish ubds-resume-function-app --python
        displayName: 'Deploy Azure Function'

      # Test the deployed function endpoint to verify deployment
      - powershell: |
          Write-Host "Testing Function Deployment 🧪"
          Start-Sleep -Seconds 30
          $response = Invoke-RestMethod -Uri "https://ubds-resume-function-app.azurewebsites.net/api/VisitorCounter?visitorId=test123"
          Write-Host "Response: $response"
        displayName: 'Test Azure Function'
 
      # Optional: List backend directory contents (for debugging)
      - powershell: |
          Write-Host "Backend directory contents:"
          Get-ChildItem -Path backend -Force
        displayName: 'List Backend Directory'
        
      # Optional: Run backend tests if available
      - powershell: |
          if (Test-Path "backend/tests/auth_tests.py") {
            pip install pytest requests
            pytest backend/tests/auth_tests.py
          }
          else {
            Write-Host "auth_tests.py not found"
          }
        displayName: 'Run Backend Auth Tests'
