name: Backend Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'iaac/**'
      - '.github/workflows/backend-infrastructure.yml'
  workflow_dispatch:

env:
  TF_WORKING_DIR: iaac

jobs:
  plan-backend-infra:
    name: Plan Backend Infrastructure
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
      
      - name: Prepare log file
        run: touch terraform.log

      - name: Terraform Plan
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform.log
        run: terraform plan -var-file="terraform.tfvars" -out=plan.tfplan
      
      - name: Show Terraform debug log
        run: cat ${{ env.TF_WORKING_DIR }}/terraform.log
      
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.tfplan

  apply-backend-infra:
    name: Apply Backend Infrastructure
    runs-on: ubuntu-latest
    needs: plan-backend-infra
    
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: .

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.tfplan
          
      - name: Output Details
        run: |
          echo "### Backend Infrastructure Deployed! 🔧" >> $GITHUB_STEP_SUMMARY
          echo "- **CosmosDB**: $(terraform output -raw cosmosdb_endpoint)" >> $GITHUB_STEP_SUMMARY
          echo "- **Function App**: $(terraform output -raw function_app_url)" >> $GITHUB_STEP_SUMMARY
