name: Backend Infrastructure

on:
  push:
    branches: [ main ]
    paths:
      - 'iaac/**'
      - '.github/workflows/backend-infrastructure.yml'
  workflow_dispatch:

jobs:
  plan-backend-infra:
    name: Plan Backend Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: List files
        run: ls -R

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: iaac
        run: terraform init

      - name: Terraform Plan
        working-directory: iaac
        env:
          TF_LOG: DEBUG
          TF_LOG_PATH: terraform.log
        run: terraform plan -var-file="terraform.tfvars" -out=plan.tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: iaac/plan.tfplan

  apply-backend-infra:
    name: Apply Backend Infrastructure
    runs-on: ubuntu-latest
    needs: plan-backend-infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: iaac

      - name: Terraform Init
        working-directory: iaac
        run: terraform init

      - name: Terraform Apply
        working-directory: iaac
        run: terraform apply -auto-approve plan.tfplan

      - name: Output Details
        working-directory: iaac
        run: |
          echo "### Backend Infrastructure Deployed! 🔧" >> $GITHUB_STEP_SUMMARY
          echo "- **CosmosDB**: $(terraform output -raw cosmosdb_endpoint)" >> $GITHUB_STEP_SUMMARY
          echo "- **Function App**: $(terraform output -raw function_app_url)" >> $GITHUB_STEP_SUMMARY
