name: Cypress E2E Tests

# Git trigger on specific paths and branch
trigger: 
  branches: 
    include:
      - main 

  paths:
    include:
      - 'frontend/iaac/**'                             # Trigger only when web files change
      - 'azure-pipelines/frontend-cypress-tests.yml'   

# use local agent on windows
pool:
  name: 'Default'

jobs:
  - job: e2etests
    displayName: "Run Cypress Tests"
    steps:
      - checkout: self 


      - task: PowerShell@2
        displayName: 'Check current directory and list files'
        inputs:
          targetType: 'inline'
          script: |
            pwd
            ls -Force


      - task: NodeTool@0 
        inputs: 
          versionSpec: '16.x'
        displayName: "SetupNode.js"
        
      - task: PowerShell@2
        displayName: 'Install dependencies'
        inputs:
          targetType: 'inline'
          script: |
            npm ci

      - task: PowerShell@2
        displayName: 'Wait for frontend to be available'
        inputs:
          targetType: 'inline'
          script: |
            for ($i = 1; $i -le 10; $i++) {
              Write-Host "Checking if frontend is available (attempt $i)..."
              try {
                Invoke-WebRequest -Uri "https://ubds-resume.azureedge.net" -UseBasicParsing -TimeoutSec 5
                Write-Host "Frontend is available!"
                break
              } catch {
                Write-Host "Not ready yet. Retry in 10 seconds..."
                Start-Sleep -Seconds 10
              }
              if ($i -eq 10) {
                Write-Error "Frontend did not become available in time."
                exit 1
              }
            }

      - task: PowerShell@2
        displayName: 'Run Cypress tests'
        inputs:
          targetType: 'inline'
          script: |
            npx cypress install
            npx cypress run `
              --config baseUrl=https://ubds-resume.azureedge.net,supportFile=false `
              --env apiUrl=https://ubds-func-app.azurewebsites.net/api/VisitorCounter
