name: Cypress E2E Tests

# Git trigger on specific paths and branch
trigger: 
  branches: 
    include:
      - main 

  paths:
    include:
      - 'frontend/iaac/**'                             # Trigger only when web files change
      - 'azure-pipelines/frontend-cypress-tests.yml'   

# use local agent on windows
pool:
  name: 'Default'


jobs:
  - job: e2e-tests
    displayName: "Run Cypress Tests"
    steps:
      - checkout: self 

      - task: NodeTool@0 
        inputs: 
          versionSpec: '16.x'
        displayName: "SetupNode.js"
        
      - powershell: |
          npm ci
        displayName: 'Install dependencies'
        
      - powershell: |
          for ($i = 1; $i -le 10; $i++) {
            Write-Host "Checking if frontend is available (attempt $i)..."
            try {
              $response = Invoke-WebRequest -Uri "https://ubds-resume.azureedge.net" -UseBasicParsing
              if ($response.StatusCode -eq 200) {
                Write-Host "Frontend is available!"
                exit 0
              }
            } catch {
              Write-Host "Not ready yet. Retry in 10 seconds..."
              Start-Sleep -Seconds 10
            }
          }
          Write-Error "Frontend did not become available in time."
          exit 1
        displayName: 'Wait for frontend (CDN) to be available'

      - powershell: |
          npx cypress install
          npx cypress run `
            --config baseUrl=https://ubds-resume.azureedge.net,supportFile=false `
            --env apiUrl=https://ubds-func-app.azurewebsites.net/api/VisitorCounter
        displayName: 'Run Cypress Tests'