# ========================
# ✅ PIPELINE: Deploy Frontend Web Pages with Terraform
# ========================
# 🎯 Trigger pipeline on changes to main branch and specific files

name: deploy-frontend-files

# Git trigger on specific paths and branch
trigger: 
  branches: 
    include:
      - main 
  
  paths:
    include:
      - 'frontend/iaac/**'                             # Trigger only when web files change
      - 'azure-pipelines/frontend-web-deploy.yml'   

# use local agent on windows
pool:
  name: 'Default'

variables:
  STORAGE_ACCOUNT_NAME: ubdswebstorage
  CDN_ENDPOINT_NAME: ubds-resume
  RESOURCE_GROUP_NAME: ubds-rg
  tfstateResourceGroup: 'tfstate-ubds-rg'
  tfstateStorageAccount: 'tfstateubds7270'
  tfstateContainer: 'tfstateubds'
  tfstateKey: 'frontend.tfstate'

jobs:
  - job: deploy_web_files
    displayName: Deploy Web Files
    pool:
      name: 'Default'
    
    steps:
      - checkout: self 

      # --- Security Scanning Steps Start ---
      - task: PowerShell@2
        displayName: Check Syft Version # Preinstalled on local agent 
        inputs:
          targetType: inline
          script: |
            syft version
      - task: PowerShell@2
        displayName: Verify working directory and list files
        inputs:
          targetType: inline
          workingDirectory: 'frontend'
          script: |
            Write-Output "Current directory:"
            pwd
            Write-Output "Files in directory:"
            ls

      - task: PowerShell@2
        displayName: Generate SBOM
        inputs:
          targetType: inline
          workingDirectory: 'frontend'
          script: |
            syft . -o json | Out-File -Encoding utf8 sbom.json
            if (Test-Path sbom.json) {
              Write-Output "sbom.json created successfully."
            } else {
              Write-Error "sbom.json not found after running syft."
            }

      - task: PowerShell@2
        displayName: Search for sbom.json in frontend recursively
        inputs:
          targetType: inline
          workingDirectory: 'frontend'
          script: |
            Write-Output "Searching for sbom.json in frontend recursively:"
            Get-ChildItem -Path . -Filter sbom.json -Recurse


      - task: PublishBuildArtifacts@1
        displayName: Upload SBOM Artifact
        inputs:
          PathtoPublish: 'frontend\sbom.json'
          ArtifactName: 'sbom-frontend'

      - task: PowerShell@2
        displayName: Check Grype Version # preinstalled on local agent 
        inputs:
          targetType: inline
          script: |
            grype version
            
      - task: PowerShell@2
        displayName: Run Grype Vulnerability Scan
        inputs:
          targetType: inline
          workingDirectory: 'frontend'
          script: |
            grype sbom:sbom.json -o table --fail-on medium

      # --- Security Scanning Steps End ---
      
      - task: AzureCLI@2
        name: AzureLodin
        inputs: 
          azureSubscription: 'ubds-sp-connection'
          scriptType: 'ps'
          scriptLocation: 'inlineScript'
          inlineScript: |
            Write-Host "Logged in to Azure CLI"
            
      - task: PowerShell@2 
        name: GetStorage
        displayName: Get Storage Account Name
        inputs:
          targetType: inline
          script: |
        
            $defaultStorage = "$(STORAGE_ACCOUNT_NAME)"

            if (!(Test-Path "frontend/iaac")) {
              Write-Host "iaac directory not found, using default storage account"
              Write-Host "##vso[task.setvariable variable=resolvedStorageAccount]$defaultStorage"
              return
            }

            Write-Host "###[group]Terraform Init"
            Set-location frontend/iaac
            
            Write-Host "Terraform location:"
            Get-Command terraform | Format-List
            terraform version

            terraform init `
              -reconfigure `
              "-backend-config=resource_group_name=$(tfstateResourceGroup)" `
              "-backend-config=storage_account_name=$(tfstateStorageAccount)" `
              "-backend-config=container_name=$(tfstateContainer)" `
              "-backend-config=key=$(tfstateKey)" `
              -input=false `
              -no-color

            if ($LASTEXITCODE -ne 0) {
              Write-Error "Terraform init failed"
              exit 1
            }
            
            Write-Host "##[endgroup]"

            Write-Host "##[group]DEBUG: List all terraform outputs"
            terraform output
            Write-Host "##[endgroup]"
            
            Write-Host "##[group]Getting Storage Account Output"
            try {
              $storage = terraform output -raw storage_account_name
              if (-not $storage) {
                throw "Empty storage account output"
              }
            } catch {
              Write-Warning "Terraform output failed or missing; falling back to default storage account"
              $storage = $defaultStorage
            }

            Write-Host "Using resolved storage account: $storage"
            Write-Host "##vso[task.setvariable variable=resolvedStorageAccount]$storage"
            Write-Host "##[endgroup]"

            
      # TROUBLESHOOTING FIX #4: Added verification steps
      # These steps ensure the storage account exists and has static website enabled
      # before attempting to upload files, providing better error messages

      - task: PowerShell@2
        displayName: Verify Storage Account
        env:
          resolvedStorageAccount: $(resolvedStorageAccount)
        inputs:
          targetType: inline
          script: |
            Write-Host "##[group]Verify Storage Account and Static Website"

            $account = "$(resolvedStorageAccount)"
            Write-Host "Checking existence of storage account: $account"
            try {
              $exists = az storage account show --name $account --query "name" -o tsv
              if (-not $exists) {
                Write-Error "Storage account $account not found"
                exit 1
              }

            } catch {
              Write-Error "Failed to verify storage account: $_"
              exit 1
            }

            Write-Host "Checking if static website is enabled on $account"
            try {
              $staticEnabled = az storage blob service-properties show --account-name $account --query "staticWebsite.enabled" -o tsv
              if ($staticEnabled -ne "true") {
                Write-Error "Static website not enabled on $account"
                exit 1
              }
            } catch {
              Write-Error "Failed to get static website status: $_"
              exit 1
            }

            Write-Host "Static website is enabled on $account"
            Write-Host "##[endgroup]"

      # --- Upload Web Files -----
      - task: PowerShell@2
        displayName: Upload Web Files
        env:
          resolvedStorageAccount: $(resolvedStorageAccount)
        inputs:
          targetType: inline
          script: |
            Write-Host "##[group]Upload Web Files"

            $account = "$(resolvedStorageAccount)"
            if (!(Test-Path "./frontend")) {
              Write-Error "Frontend folder not found"
              exit 1
            }

            Write-Host "Uploading files to storage account: $account"
            $success = $false

            try {
              az storage blob upload-batch `
                --account-name $account `
                --auth-mode login `
                --source ./frontend `
                --destination '$web' `
                --overwrite
              $success = $true
            } catch {
              Write-Warning "Login auth failed, trying with account key..."
            }

            if (-not $success) {
              $rg = az storage account show --name $account --query "resourceGroup" -o tsv
              $key = az storage account keys list --account-name $account --resource-group $rg --query "[0].value" -o tsv

              az storage blob upload-batch `
                --account-name $account `
                --account-key $key `
                --source ./frontend `
                --destination '$web' `
                --overwrite
            }
            Write-Host "Upload completed"
            Write-Host "##[endgroup]"

      # ---- Purge CDN cache-----
      - task: PowerShell@2
        displayName: Purge CDN Cache
        inputs:
          targetType: inline
          script: |
            Write-Host "##[group]Purge CDN Cache"

            $cdn = "$(CDN_ENDPOINT_NAME)"
            $profile = "$(CDN_PROFILE_NAME)"
            $rg = "$(RESOURCE_GROUP_NAME)"

            Write-Host "Checking CDN endpoint $cdn in profile $profile and resource group $rg"
            $exists = az cdn endpoint show --resource-group $rg --profile-name $profile --name $cdn --query "name" -o tsv 2>$null

            if ($exists) {
              Write-Host "Purging CDN cache for endpoint $cdn"
              az cdn endpoint purge `
                --resource-group $rg `
                --profile-name $profile `
                --name $cdn `
                --content-paths "/*" `
                --no-wait
            } else {
              Write-Warning "CDN endpoint not found, skipping purge"
            }
            Write-Host "##[endgroup]"

      # ---- Deployment Summary -------
      - task: PowerShell@2
        displayName: Deployment Summary
        inputs:
          targetType: inline
          script: |
            $cdnUrl = "https://$(CDN_ENDPOINT_NAME).azureedge.net"
            Write-Host "##vso[task.setvariable variable=cdnUrl]$cdnUrl"
            Write-Host "Frontend deployed to $cdnUrl"

  # # Optional separate job for NPM audit:
  # - job: dependency_scan
  #   displayName: JavaScript Dependency Scan
  #   pool:
  #     name: 'Default'

  #     steps:
  #     - task: NodeTool@0
  #       inputs:
  #         versionSpec: '22.x'

  #     - task: PowerShell@2
  #       displayName: Install Node Modules
  #       inputs:
  #         targetType: inline
  #         workingDirectory: 'frontend'
  #         script: |
  #           npm install

  #     - task: PowerShell@2
  #       displayName: NPM Audit
  #       inputs:
  #         targetType: inline
  #         workingDirectory: 'frontend'
  #         script: |
  #           npm audit --audit-level=moderate